# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'car-sales' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'SnapKit'
  pod 'Toast-Swift'
  # Pods for car-sales

end
